steps:
  # Build orchestration service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/quantum-sentinel-orchestration:latest'
      - '-f'
      - 'services/orchestration/Dockerfile'
      - 'services/orchestration'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'quantum-sentinel-orchestration'
      - '--image'
      - 'gcr.io/$PROJECT_ID/quantum-sentinel-orchestration:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--concurrency'
      - '100'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '1'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,SCAN_TIMEOUT=14400'

images:
  - 'gcr.io/$PROJECT_ID/quantum-sentinel-orchestration:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50

timeout: 1800s
